// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO auth_db (id, worker_group, api_key_hash)
VALUES ($1, $2, $3)
RETURNING id, worker_group, api_key_hash, created_at
`

type CreateWorkerParams struct {
	ID          uuid.UUID
	WorkerGroup string
	ApiKeyHash  string
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (AuthDb, error) {
	row := q.db.QueryRowContext(ctx, createWorker, arg.ID, arg.WorkerGroup, arg.ApiKeyHash)
	var i AuthDb
	err := row.Scan(
		&i.ID,
		&i.WorkerGroup,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}
