// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type AuthDb struct {
	ID          uuid.UUID
	WorkerGroup string
	ApiKeyHash  string
	CreatedAt   sql.NullTime
	IsDisabled  sql.NullBool
	Expiry      sql.NullTime
	UpdatedAt   sql.NullTime
}

type Organization struct {
	ID           uuid.UUID
	OrgName      string
	RegNumber    sql.NullString
	ContactEmail string
	Website      sql.NullString
	IsVerified   sql.NullBool
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
