// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type AuthDb struct {
	ID          uuid.UUID
	WorkerGroup string
	ApiKeyHash  string
	CreatedAt   sql.NullTime
}
